version: "3.2"
services:
  entry:
    image: haproxytech/haproxy-debian:2.4
    volumes:
      - /home/ubuntu/Desktop/test/haproxytest:/usr/local/etc/haproxy
    ports:
      - "80:80"
      - "5555:5555"
    depends_on:
      - "swiftbase.com"
      
      
  swiftbase.com:
    image: haproxytech/haproxy-debian:2.4
    volumes:
      - /home/ubuntu/Desktop/test/haproxytest/swiftbase:/usr/local/etc/haproxy
    depends_on:
      - "splash"
      - "account"
      - "postgres"
      
  splash:
    image: bisratawoke/splash:latest
  
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=blackkush
      - POSTGRES_USER=postgres
      - POSTGRES_DB=project_base
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    
  account:
    image: bisratawoke/account:latest
  
  project-managment:
    image: bisratawoke/project-managment:latest

volumes:
  postgres_vol:
    external: true
